unifi_wifi:
  - name: myhouse
    site: default
    scan_interval: 300
    timeout: 20
    host: !secret unifi_host
    port: 443
    username: !secret unifi_username
    password: !secret unifi_password
    unifi_os: true
    verify_ssl: false
    force_provision: true
    managed_aps:
      - name: udm
        mac: !secret unifi_udm_mac
      - name: u6lite
        mac: !secret unifi_u6l_mac
    monitored_ssids:
      - name: Guest
        fill_color: '#490361'
        back_color: '#9cedf0'
      - name: StuffandThings
        preshared_keys:
          - name: NoT
            fill_color: '#a84032'
            back_color: '#bfb7b6'
          - name: IoT


# logger:
  # logs:
    # custom_components.unifi_wifi: debug


automation:
  - id: 'guest_wifi_monthly_random_password'
    alias: Guest Wifi
    description: On the first of each month set a random password for the Guest Wifi
    mode: single
    trigger:
      - platform: template
        value_template: '{{ now().day == 1 }}'
    action:
      - service: button.press
        target:
          entity_id: button.guest_wifi_random


template:
  button:
    - name: 'Guest Wifi Random'
      unique_id: guest_wifi_random
      press:
        - service: unifi_wifi.wlan_password
          data:
            target: image.myhouse_guest_wifi
            method: word

    - name: 'Guest Wifi Default'
      unique_id: guest_wifi_default
      press:
        - service: unifi_wifi.wlan_password
          data:
            target: image.myhouse_guest_wifi
            password: "SOME-KNOWN-DEFAULT"

    - name: 'Guest Wifi Custom'
      unique_id: guest_wifi_custom
      press:
        - service: unifi_wifi.wlan_password
          data:
            target: image.myhouse_guest_wifi
            password: "{{states('input_text.guest_wifi')}}"
        - service: input_text.set_value
          data:
            entity_id: input_text.guest_wifi
            value: ''


  sensor:
    # https://community.home-assistant.io/t/unifi-network-number-of-active-clients-on-guest-ssid/377074
    # requires native UniFi Network integration https://www.home-assistant.io/integrations/unifi
    - name: Guest Wifi Client Count
      unique_id: guest_wifi_client_count
      state: >
        {{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.essid', 'eq', '<GUEST SSID HERE>') | list | count }}
      # state: >
      #   {{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.essid', 'eq', '<PPSK SSID HERE>') | selectattr('attributes.vlan', 'eq', <GUEST NETWORK VLAN ID HERE>) | list | count }}


input_text:
  guest_wifi:
    name: guest_wifi
    initial: ''
    icon: mdi:form-textbox-password
    mode: password