unifi_wifi:
  base_url: !secret unifi_baseurl
  username: !secret unifi_username
  password: !secret unifi_password
  # site: default
  # unifi_os: true
  # verify_ssl: false
  networks:
    - ssid: Guest


automation:
  - id: 'guest_wifi'
    alias: Guest Wifi
    description: On the first of each month set a random password for the Guest Wifi
    mode: single
    trigger:
      - platform: template
        value_template: '{{ now().day == 1 }}'
    action:
      - service: button.press
        target:
          entity_id: button.guest_wifi_random


template:
  button:
    - name: 'Guest Wifi Random'
      unique_id: guest_wifi_random
      press:
        - service: unifi_wifi.random_password
          data:
            ssid: Guest
            method: word
        - delay: '00:00:10'
        - service: homeassistant.update_entity
          data:
            entity_id:
              - binary_sensor.guest_wifi
              - image.guest_wifi

    - name: 'Guest Wifi Default'
      unique_id: guest_wifi_default
      press:
        - service: unifi_wifi.custom_password
          data:
            ssid: Guest
            password: "weinerschnitzel"
        - delay: '00:00:10'
        - service: homeassistant.update_entity
          data:
            entity_id:
              - binary_sensor.guest_wifi
              - image.guest_wifi

    - name: 'Guest Wifi Custom'
      unique_id: guest_wifi_custom
      press:
        - service: unifi_wifi.custom_password
          data:
            ssid: Guest
            password: "{{states('input_text.guest_wifi')}}"
        - delay: '00:00:10'
        - service: homeassistant.update_entity
          data:
            entity_id:
              - binary_sensor.guest_wifi
              - image.guest_wifi
        - service: input_text.set_value
          data:
            entity_id: input_text.guest_wifi
            value: ''


input_text:
  guest_wifi:
    name: guest_wifi
    initial: ''
    icon: mdi:form-textbox-password
    mode: password
