unifi_wifi:
  - name: myhouse
    site: default
    scan_interval: 300
    host: !secret unifi_host
    port: 443
    username: !secret unifi_username
    password: !secret unifi_password
    unifi_os: true
    verify_ssl: false
    monitored_ssids:
      - name: Guest


# logger:
  # logs:
    # custom_components.unifi_wifi_next: debug


automation:
  - id: 'guest_wifi_monthly_random_password'
    alias: Guest Wifi
    description: On the first of each month set a random password for the Guest Wifi
    mode: single
    trigger:
      - platform: template
        value_template: '{{ now().day == 1 }}'
    action:
      - service: button.press
        target:
          entity_id: button.guest_wifi_random


template:
  button:
    - name: 'Guest Wifi Random'
      unique_id: guest_wifi_random
      press:
        - service: unifi_wifi.random_password
          data:
            name: myhouse
            ssid: Guest
            method: word

    - name: 'Guest Wifi Default'
      unique_id: guest_wifi_default
      press:
        - service: unifi_wifi.custom_password
          data:
            name: myhouse
            ssid: Guest
            password: "SOME-KNOWN-DEFAULT"

    - name: 'Guest Wifi Custom'
      unique_id: guest_wifi_custom
      press:
        - service: unifi_wifi.custom_password
          data:
            name: myhouse
            ssid: Guest
            password: "{{states('input_text.guest_wifi')}}"
        - service: input_text.set_value
          data:
            entity_id: input_text.guest_wifi
            value: ''


input_text:
  guest_wifi:
    name: guest_wifi
    initial: ''
    icon: mdi:form-textbox-password
    mode: password